# Generated by Django 4.2.25 on 2025-10-16 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_comments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comments",
            options={"ordering": ["created_on"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["created_on"]},
        ),
    ]
