# Generated by Django 4.2.25 on 2025-10-26 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_about_profile_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="about",
            old_name="profile_image",
            new_name="profile_images",
        ),
    ]
